# Generated by Django 3.1.1 on 2020-10-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_album',
            field=models.ImageField(default='static/assets/default/img_album_default-min.jpg', upload_to='assets/img_artistes', verbose_name="Image de l'album"),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='image_artiste',
            field=models.ImageField(default='static/default/img_artiste_default-min.jpg', null=True, upload_to='assets/img_albums', verbose_name="Image de l'artiste"),
        ),
    ]
