# Generated by Django 3.1.1 on 2020-10-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0002_auto_20201015_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='id_genre',
        ),
        migrations.RemoveField(
            model_name='album',
            name='id_label',
        ),
        migrations.AddField(
            model_name='album',
            name='spotify_id_album',
            field=models.TextField(null=True, verbose_name="ID Spotify de l'album"),
        ),
        migrations.AddField(
            model_name='artiste',
            name='spotify_id_artiste',
            field=models.TextField(null=True, verbose_name="ID Spotify de l'artiste"),
        ),
        migrations.AlterField(
            model_name='album',
            name='date_publication_album',
            field=models.CharField(max_length=10, null=True, verbose_name="Date de parution de l'album"),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='compteur_recherche',
            field=models.IntegerField(default=1, verbose_name='Nombre de fois'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
