# Generated by Django 3.1.1 on 2020-10-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0002_auto_20201015_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image_playlist',
            field=models.ImageField(default='/assets/default/img_album_default-min.jpg', upload_to='assets/img_playlists', verbose_name='Image de la playlist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='nom_playlist',
            field=models.CharField(default=None, max_length=50, verbose_name='Nom de la playlist'),
            preserve_default=False,
        ),
    ]
