# Generated by Django 3.1.1 on 2020-10-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiques', '0004_auto_20201017_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='lien_album',
            field=models.TextField(null=True, verbose_name="Lien de l'album sur AllForMusic"),
        ),
    ]
